# *Motor Design Data Driven*

## 1. Análisis EDA

### 1.1. Librerías

In [1]:
# Librerías necesarias
import os
import re  # Import the regular expression module

import pandas as pd
import numpy as np
import math

import matplotlib
matplotlib.use('TKAgg')
import matplotlib.pyplot as plt
from matplotlib.ticker import ScalarFormatter
import seaborn as sns

### 1.2. Lectura de fichero

In [2]:
# Definir las rutas base y de las carpetas
base_path = os.getcwd()  # Se asume que el notebook se ejecuta desde la carpeta 'EDA'
db_path = os.path.join(base_path, "DB_EDA")
fig_path = os.path.join(base_path, "Figuras_EDA")

# Ruta al archivo de la base de datos
data_file = os.path.join(db_path, "design_DB_400_Optimizado.csv")
print(data_file)

# Ruta al archivo de las figuras
figure_path = os.path.join(fig_path, "400_MOT_Optimizado")

C:\Users\s00244\Documents\GitHub\MotorDesignDataDriven\Notebooks\1.EDA\DB_EDA\design_DB_400_Optimizado.csv

In [3]:
# Lectura del archivo CSV
try:
    df = pd.read_csv(data_file)
    print("Archivo cargado exitosamente.")
except FileNotFoundError:
    print("Error: Archivo no encontrado. Revisa la ruta del archivo.")
except pd.errors.ParserError:
    print("Error: Problema al analizar el archivo CSV. Revisa el formato del archivo.")
except Exception as e:
    print(f"Ocurrió un error inesperado: {e}")

Archivo cargado exitosamente.

### 1.3. Exploración inicial de datos

In [4]:
# Exploración inicial de datos

# Mostrar las primeras filas del DataFrame
print("\nPrimeras filas del DataFrame:")
display(df.head())

Primeras filas del DataFrame:

,x1::OSD,x2::Dint,x3::L,x4::tm,x5::hs2,x6::wt,x7::Nt,x8::Nh,m1::Drot,m2::Dsh,...,m6::GFF,p1::W,p2::Tnom,p3::nnom,p4::GFF,p5::BSP_T,p6::BSP_n,p7::BSP_Mu,p8::MSP_n,p9::UWP_Mu
0,51.690000,21.320000,25.140000,3.040000,11.260000,3.170000,18,4,20.320000,8.148571,...,48.841316,0.547046,0.11,3960.0,51.796941,0.622691,3266.3018,80.883851,5059.7498,91.466253
1,56.502470,22.613729,39.462243,2.537889,13.319987,2.909111,18,4,21.613729,10.076885,...,34.051748,0.802811,0.11,3960.0,35.937102,1.029602,2021.8792,77.284656,2990.9938,NaN
2,55.385007,21.566434,31.920320,2.741117,10.541636,2.004243,6,6,20.566434,8.922362,...,21.838120,0.627795,0.11,3960.0,23.905641,0.369550,11299.0470,89.507789,10000.0000,87.383473
3,58.660823,24.610769,17.825636,3.236242,11.840792,2.327503,11,8,23.610769,10.106636,...,42.164530,0.537537,0.11,3960.0,45.877325,0.553070,8555.1022,88.670041,10000.0000,90.207256
4,59.745991,22.251184,21.641420,2.755130,13.803262,3.929361,13,5,21.251184,9.383442,...,34.987853,0.586384,0.11,3960.0,36.268856,0.516334,5125.1648,85.616573,7697.1508,91.063259

In [5]:
# Información general del DataFrame
print("\nInformación general del DataFrame:")
df.info()

Información general del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   x1::OSD     400 non-null    float64
 1   x2::Dint    400 non-null    float64
 2   x3::L       400 non-null    float64
 3   x4::tm      400 non-null    float64
 4   x5::hs2     400 non-null    float64
 5   x6::wt      400 non-null    float64
 6   x7::Nt      400 non-null    int64
 7   x8::Nh      400 non-null    int64
 8   m1::Drot    400 non-null    float64
 9   m2::Dsh     400 non-null    float64
 10  m3::he      400 non-null    float64
 11  m4::Rmag    400 non-null    float64
 12  m5::Rs      400 non-null    float64
 13  m6::GFF     400 non-null    float64
 14  p1::W       315 non-null    float64
 15  p2::Tnom    400 non-null    float64
 16  p3::nnom    400 non-null    float64
 17  p4::GFF     315 non-null    float64
 18  p5::BSP_T   315 non-null    float64
 19  p6::BSP_n   315 non-null    float64
 20  p7::BSP_Mu  315 non-null    float64
 21  p8::MSP_n   315 non-null    float64
 22  p9::UWP_Mu  229 non-null    float64
dtypes: float64(21), int64(2)
memory usage: 72.0 KB

In [6]:
# Estadísticas descriptivas del DataFrame
print("\nEstadísticas descriptivas:")
display(df.describe())

Estadísticas descriptivas:

,x1::OSD,x2::Dint,x3::L,x4::tm,x5::hs2,x6::wt,x7::Nt,x8::Nh,m1::Drot,m2::Dsh,...,m6::GFF,p1::W,p2::Tnom,p3::nnom,p4::GFF,p5::BSP_T,p6::BSP_n,p7::BSP_Mu,p8::MSP_n,p9::UWP_Mu
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000,400.000000,...,400.000000,315.000000,4.000000e+02,400.0,315.000000,315.000000,315.000000,315.000000,315.000000,229.000000
mean,52.045448,26.107137,19.309024,2.839335,8.084004,3.450714,11.30750,4.372500,25.107137,11.969286,...,41.608718,0.461910,1.100000e-01,3960.0,45.315907,0.388500,12968.090069,86.927058,8210.782532,87.725264
std,5.385231,3.767904,9.328129,0.485147,2.543092,0.882392,6.25586,1.691418,3.767904,2.690761,...,10.407208,0.201373,4.168550e-17,0.0,11.379477,0.296447,9769.825991,4.801350,2514.007273,3.862631
min,45.000638,21.202112,10.001446,2.003981,5.002324,2.000861,5.00000,3.000000,20.202112,8.032018,...,20.025111,0.212332,1.100000e-01,3960.0,22.137618,0.055486,1073.413400,63.186472,1502.009500,67.880190
25%,46.015232,22.952733,10.342912,2.388129,6.022688,2.708583,6.75000,3.000000,21.952733,10.112943,...,33.105689,0.284594,1.100000e-01,3960.0,35.534630,0.164718,5214.120500,85.142567,6576.434900,85.962501
50%,52.321095,25.795720,16.409816,2.951084,7.356168,3.273594,9.00000,4.000000,24.795720,11.387427,...,44.068169,0.419143,1.100000e-01,3960.0,46.357420,0.305577,9719.365200,88.313624,10000.000000,88.984249
75%,57.234552,27.957449,26.155611,3.271505,9.723094,4.229813,14.00000,5.000000,26.957449,13.277137,...,50.759750,0.612398,1.100000e-01,3960.0,55.168937,0.533057,19393.462000,90.214936,10000.000000,90.443224
max,59.980738,41.449266,39.715758,3.498642,14.954719,4.993890,30.00000,9.000000,40.449266,23.390318,...,54.969679,0.989638,1.100000e-01,3960.0,64.262915,1.589269,39928.859000,93.076507,10000.000000,92.823456

### 1.4. Visualización de los datos

In [7]:
# Estilo visual
sns.set(style='whitegrid')

# Agrupar columnas por prefijo
x_cols = [col for col in df.columns if col.startswith('x') and df[col].dtype in ['float64', 'int64']]
m_cols = [col for col in df.columns if col.startswith('m') and df[col].dtype in ['float64', 'int64']]
p_cols = [col for col in df.columns if col.startswith('p') and df[col].dtype in ['float64', 'int64']]

def plot_variable_group(columns, group_name):
    if not columns:
        print(f"No hay variables para el grupo '{group_name}'")
        return

    n = len(columns)
    cols = 3  # número de columnas de subplots
    rows = math.ceil(n / cols)

    fig, axes = plt.subplots(rows, cols, figsize=(cols * 6, rows * 4))
    axes = axes.flatten()

    for i, col in enumerate(columns):
        ax = axes[i]
        sns.histplot(df[col], kde=True, ax=ax, color='skyblue', edgecolor='black')
        ax.set_title(f'Distribución de {col}', fontsize=12)
        ax.ticklabel_format(style='scientific', axis='x', scilimits=(0, 0))
        ax.set_xlabel(col, fontsize=10)
        ax.set_ylabel('Frecuencia', fontsize=10)

    # Eliminar ejes vacíos
    for j in range(i + 1, len(axes)):
        fig.delaxes(axes[j])

    fig.suptitle(f'Distribuciones del grupo "{group_name}"', fontsize=16)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    # Guardar la figura en la carpeta 'Figuras_EDA/(La carpeta que corresponda)'
    figure_file = os.path.join(figure_path, f"Distribuciones del grupo_{group_name}.png")
    plt.savefig(figure_file, dpi =1080)
    plt.close()
    #plt.show()

# Generar subplots por grupo
plot_variable_group(x_cols, 'x')
plot_variable_group(m_cols, 'm')
plot_variable_group(p_cols, 'p')

In [8]:
def plot_heatmap(subset_df, title, xlabel, ylabel):
    if subset_df.empty:
        print(f"No hay datos para {title}")
        return

    plt.figure(figsize=(max(10, 0.5 * subset_df.shape[1]), max(6, 0.4 * subset_df.shape[0])))
    sns.heatmap(subset_df, annot=True, fmt=".2f", cmap='coolwarm', linewidths=0.5, 
                cbar_kws={'label': 'Correlación'}, annot_kws={"size": 8})
    plt.title(title, fontsize=14, weight='bold')
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.xticks(rotation=45, ha='right')
    plt.yticks(rotation=0)
    plt.tight_layout()
    # Guardar la figura en la carpeta 'Figuras_EDA/(La carpeta que corresponda)'
    figure_file = os.path.join(figure_path, f"{title}.png")
    plt.savefig(figure_file, dpi =1080)
    plt.close()
    #plt.show()

# Correlación p-x
if p_cols and x_cols:
    corr_px = df[p_cols + x_cols].corr().loc[p_cols, x_cols]
    plot_heatmap(corr_px, 'Mapa de calor_Variables p vs x', 'x', 'p')

# Correlación p-m
if p_cols and m_cols:
    corr_pm = df[p_cols + m_cols].corr().loc[p_cols, m_cols]
    plot_heatmap(corr_pm, 'Mapa de calor_Variables p vs m', 'm', 'p')

# Correlación p-p
if p_cols:
    corr_pp = df[p_cols].corr()
    plot_heatmap(corr_pp, 'Mapa de calor_Variables p vs p', 'p', 'p')

### 1.5. Preprocesado de los datos

In [9]:
# Verificar y corregir tipos de datos incorrectos usando expresiones regulares
def correct_dtype_regex(df):
    numeric_regex = re.compile(r'^-?\d+(\.\d+)?$')
    for col in df.columns:
        if df[col].dtype == 'object':
            if df[col].dropna().apply(lambda x: bool(numeric_regex.match(str(x)))).all():
                df[col] = pd.to_numeric(df[col])
                print(f"Columna '{col}' convertida a tipo numérico exitosamente usando regex.")
            else:
                print(f"Columna '{col}' no puede ser convertida directamente a numérico.")
    return df

df = correct_dtype_regex(df)
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   x1::OSD     400 non-null    float64
 1   x2::Dint    400 non-null    float64
 2   x3::L       400 non-null    float64
 3   x4::tm      400 non-null    float64
 4   x5::hs2     400 non-null    float64
 5   x6::wt      400 non-null    float64
 6   x7::Nt      400 non-null    int64
 7   x8::Nh      400 non-null    int64
 8   m1::Drot    400 non-null    float64
 9   m2::Dsh     400 non-null    float64
 10  m3::he      400 non-null    float64
 11  m4::Rmag    400 non-null    float64
 12  m5::Rs      400 non-null    float64
 13  m6::GFF     400 non-null    float64
 14  p1::W       315 non-null    float64
 15  p2::Tnom    400 non-null    float64
 16  p3::nnom    400 non-null    float64
 17  p4::GFF     315 non-null    float64
 18  p5::BSP_T   315 non-null    float64
 19  p6::BSP_n   315 non-null    float64
 20  p7::BSP_Mu  315 non-null    float64
 21  p8::MSP_n   315 non-null    float64
 22  p9::UWP_Mu  229 non-null    float64
dtypes: float64(21), int64(2)
memory usage: 72.0 KB

None

In [10]:
# Optimización del uso de memoria reduciendo tamaño de tipos de datos
for col in df.select_dtypes(include=['int64', 'float64']).columns:
    if df[col].dtype == 'int64':
        df[col] = df[col].astype('int32')
        print(f"Columna '{col}' convertida de int64 a int32.")
    elif df[col].dtype == 'float64':
        df[col] = df[col].astype('float32')
        print(f"Columna '{col}' convertida de float64 a float32.")
display(df.info())

Columna 'x1::OSD' convertida de float64 a float32.
Columna 'x2::Dint' convertida de float64 a float32.
Columna 'x3::L' convertida de float64 a float32.
Columna 'x4::tm' convertida de float64 a float32.
Columna 'x5::hs2' convertida de float64 a float32.
Columna 'x6::wt' convertida de float64 a float32.
Columna 'x7::Nt' convertida de int64 a int32.
Columna 'x8::Nh' convertida de int64 a int32.
Columna 'm1::Drot' convertida de float64 a float32.
Columna 'm2::Dsh' convertida de float64 a float32.
Columna 'm3::he' convertida de float64 a float32.
Columna 'm4::Rmag' convertida de float64 a float32.
Columna 'm5::Rs' convertida de float64 a float32.
Columna 'm6::GFF' convertida de float64 a float32.
Columna 'p1::W' convertida de float64 a float32.
Columna 'p2::Tnom' convertida de float64 a float32.
Columna 'p3::nnom' convertida de float64 a float32.
Columna 'p4::GFF' convertida de float64 a float32.
Columna 'p5::BSP_T' convertida de float64 a float32.
Columna 'p6::BSP_n' convertida de float64 a float32.
Columna 'p7::BSP_Mu' convertida de float64 a float32.
Columna 'p8::MSP_n' convertida de float64 a float32.
Columna 'p9::UWP_Mu' convertida de float64 a float32.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   x1::OSD     400 non-null    float32
 1   x2::Dint    400 non-null    float32
 2   x3::L       400 non-null    float32
 3   x4::tm      400 non-null    float32
 4   x5::hs2     400 non-null    float32
 5   x6::wt      400 non-null    float32
 6   x7::Nt      400 non-null    int32
 7   x8::Nh      400 non-null    int32
 8   m1::Drot    400 non-null    float32
 9   m2::Dsh     400 non-null    float32
 10  m3::he      400 non-null    float32
 11  m4::Rmag    400 non-null    float32
 12  m5::Rs      400 non-null    float32
 13  m6::GFF     400 non-null    float32
 14  p1::W       315 non-null    float32
 15  p2::Tnom    400 non-null    float32
 16  p3::nnom    400 non-null    float32
 17  p4::GFF     315 non-null    float32
 18  p5::BSP_T   315 non-null    float32
 19  p6::BSP_n   315 non-null    float32
 20  p7::BSP_Mu  315 non-null    float32
 21  p8::MSP_n   315 non-null    float32
 22  p9::UWP_Mu  229 non-null    float32
dtypes: float32(21), int32(2)
memory usage: 36.1 KB

None

In [11]:
# Verificación de valores faltantes y duplicados
print("\nValores faltantes por columna:")
display(df.isnull().sum())

Valores faltantes por columna:

x1::OSD         0
x2::Dint        0
x3::L           0
x4::tm          0
x5::hs2         0
x6::wt          0
x7::Nt          0
x8::Nh          0
m1::Drot        0
m2::Dsh         0
m3::he          0
m4::Rmag        0
m5::Rs          0
m6::GFF         0
p1::W          85
p2::Tnom        0
p3::nnom        0
p4::GFF        85
p5::BSP_T      85
p6::BSP_n      85
p7::BSP_Mu     85
p8::MSP_n      85
p9::UWP_Mu    171
dtype: int64

In [12]:
print("\nCantidad de filas duplicadas:")
display(df.duplicated().sum())

Cantidad de filas duplicadas:

np.int64(0)

In [13]:
# Identifica las filas con valores NaN en cualquier matriz
rows_with_nan = df[df.isnull().any(axis=1)].index

# Obtiene el conjunto de todos los índices con NaN
all_nan_indices = set(rows_with_nan)
all_nan_indices = sorted(list(all_nan_indices))

# Elimina las filas con valores NaN.
df_cleaned = df.drop(index=all_nan_indices)

display(df_cleaned.info())

<class 'pandas.core.frame.DataFrame'>
Index: 229 entries, 0 to 396
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   x1::OSD     229 non-null    float32
 1   x2::Dint    229 non-null    float32
 2   x3::L       229 non-null    float32
 3   x4::tm      229 non-null    float32
 4   x5::hs2     229 non-null    float32
 5   x6::wt      229 non-null    float32
 6   x7::Nt      229 non-null    int32
 7   x8::Nh      229 non-null    int32
 8   m1::Drot    229 non-null    float32
 9   m2::Dsh     229 non-null    float32
 10  m3::he      229 non-null    float32
 11  m4::Rmag    229 non-null    float32
 12  m5::Rs      229 non-null    float32
 13  m6::GFF     229 non-null    float32
 14  p1::W       229 non-null    float32
 15  p2::Tnom    229 non-null    float32
 16  p3::nnom    229 non-null    float32
 17  p4::GFF     229 non-null    float32
 18  p5::BSP_T   229 non-null    float32
 19  p6::BSP_n   229 non-null    float32
 20  p7::BSP_Mu  229 non-null    float32
 21  p8::MSP_n   229 non-null    float32
 22  p9::UWP_Mu  229 non-null    float32
dtypes: float32(21), int32(2)
memory usage: 22.4 KB

None

In [14]:
# Tabla de estadísticas descriptivas
print("\nTabla de estadísticas descriptivas finales:")
display(df_cleaned.describe().T)

Tabla de estadísticas descriptivas finales:

,count,mean,std,min,25%,50%,75%,max
x1::OSD,229.0,53.290291,4.666716,45.004791,50.021187,54.097923,57.364086,59.908478
x2::Dint,229.0,26.042513,3.876286,21.212650,22.962980,25.475109,28.097462,41.449265
x3::L,229.0,19.403172,8.855961,10.008005,11.108705,17.103909,25.243786,39.715759
x4::tm,229.0,2.863762,0.463276,2.007371,2.480048,2.967036,3.250827,3.495281
x5::hs2,229.0,8.435880,2.224621,5.011013,6.737050,8.005257,9.963131,14.513173
x6::wt,229.0,3.332908,0.860367,2.000861,2.617739,3.217130,3.929360,4.977125
x7::Nt,229.0,10.781659,5.319231,5.000000,7.000000,9.000000,14.000000,30.000000
x8::Nh,229.0,4.917031,1.851296,3.000000,3.000000,4.000000,6.000000,9.000000
m1::Drot,229.0,25.042513,3.876286,20.212650,21.962980,24.475109,27.097462,40.449265
m2::Dsh,229.0,11.874270,2.850648,8.032018,9.821224,11.188096,13.380566,23.390318
m3::he,229.0,5.188011,1.676549,3.507639,3.854693,4.701980,5.949516,11.150534
m4::Rmag,229.0,11.805315,1.932602,9.365659,10.284057,11.448117,12.858143,19.572596
m5::Rs,229.0,21.457134,2.160673,16.989998,19.528099,21.598860,23.262533,26.225462
m6::GFF,229.0,41.160061,9.520947,20.060358,34.209648,42.462852,49.689999,54.951786
p1::W,229.0,0.473687,0.168985,0.233749,0.337880,0.432938,0.593234,0.864733
p2::Tnom,229.0,0.110000,0.000000,0.110000,0.110000,0.110000,0.110000,0.110000
p3::nnom,229.0,3960.000000,0.000000,3960.000000,3960.000000,3960.000000,3960.000000,3960.000000
p4::GFF,229.0,47.368244,10.912129,22.137617,38.329826,50.024490,56.526546,64.262917
p5::BSP_T,229.0,0.379866,0.210079,0.111801,0.229818,0.327082,0.476269,1.149111
p6::BSP_n,229.0,10859.899414,6739.874512,2766.515625,5859.098145,9147.068359,14343.701172,36048.593750
p7::BSP_Mu,229.0,88.489883,3.301752,73.469490,87.260284,89.204002,90.755333,93.076508
p8::MSP_n,229.0,8552.818359,1945.926636,4047.442383,7013.307129,10000.000000,10000.000000,10000.000000
p9::UWP_Mu,229.0,87.725258,3.862631,67.880188,85.962502,88.984245,90.443222,92.823456

### 1.6. Almacenar el preprocesado

In [15]:
# Guardar DataFrame preprocesado
print("\nDataFrame después del preprocesamiento:")
# Ruta al archivo de la base de datos
data_cleaned_file = os.path.join(db_path, 'design_DB_preprocessed.csv')
df_cleaned.to_csv(data_cleaned_file, index=False)
# Confirmación de preprocesamiento
print("\nPreprocesamiento completado exitosamente. Archivo 'datos_preprocesados.csv' guardado.")

DataFrame después del preprocesamiento:

Preprocesamiento completado exitosamente. Archivo 'datos_preprocesados.csv' guardado.

-------------------------------------------------------------------------------------------------------------------------